### ISSUE TITLE
Internationalize the validators and email verification

### ISSUE THREAD

**Issue by wer-mathurin** [bahricanyesil/flutter-animated-login#65]
@bahricanyesil 

When validating the email the error message is hardcoded.

`if (!isValid) return 'Please enter a valid email'`

I propose to add an option to the LoginText(emailValidation:)  or something

Same thing for Validators
`if (!containsUpperCase) return 'Must contain upper case character.';`

The only tricky one the length validation
`'Must be longer than or equal to $length characters';`

But for this one, in the LoginText we can provide a `String Function(length)? instead of a String?.`

**Comment by wer-mathurin** [comment]
@bahricanyesil Any updates on this one?

**Comment by bahricanyesil** [comment]
I'm so sorry @wer-mathurin. I missed this issue because of the university staff. 

First of all, you can use ValidatorModel to provide customized validations. However, I will add the things you stated to the built-in validation in the message. You will be able to change the message without handling the errors manually.

PR will be merged and the new version will be published today. @wer-mathurin

**Comment by bahricanyesil** [comment]
Hi again @wer-mathurin, the change you requested is implemented and merged. It is now live with the update to version 1.5.5. Thanks.
